version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_SERVER: host.docker.internal
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "8181:8080"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    depends_on:
      - postgres

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "9001:8080"
    environment:
      API_URL: http://localhost:8080/api/v1/openapi
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge